BlackHoles/Models/Issue.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BlackHoles.Models
{
  public class Issue
  {
    [Key, Column(Order = 1), Display(Name = "Год")]
    public int Year   { get; set; }

    [Key, Column(Order = 2), Display(Name = "№")]
    public int Number { get; set; }

    [Display(Name = "Формируется в данное время")]
    public bool Active { get; set; }
  }
}

BlackHoles/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlackHoles.DataContexts;
using BlackHoles.Utils;
using AutoMapper;
using BlackHoles.Models;

namespace BlackHoles.Controllers
{
  [Authorize]
  public class AuthorsController : Controller
  {
    private IssuesDb db = new IssuesDb();

    // GET: Authors
    public ActionResult Index()
    {
      return View(db.Authors.Include(a => a.Owner).FilterByOwner(User).OrderBy(a => a.RusSurname).ToList());
    }

    // GET: Authors/Details/5
    public ActionResult Details(int? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Author author = db.Authors.Include(x => x.Owner).Include(x => x.Articles).FilterByOwner(User).FirstOrDefault(a => a.Id == id);
      if (author == null)
      {
        return HttpNotFound();
      }
      return View(author);
    }

    // GET: Authors/Create
    public ActionResult Create()
    {
      return View();
    }

    // POST: Authors/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create([Bind(Include = "Id,Email,RusSurname,RusInitials,RusOrgName,RusSubdivision,RusPosition,EnuSurname,EnuInitials,EnuOrgName,ScienceDegree,Phone,OrganizationKind,Postcode,PostalAddress", Exclude="Owner")] Author author)
    {
      var userId = User.GetUserId();
      var user = db.Users.Find(userId);
      author.Owner = user;

      this.Revalidate(author);

      if (ModelState.IsValid)
      {
        db.Authors.Add(author);
        db.SaveChanges();
        return RedirectToAction("Details", new { id = author.Id });
      }

      return View(author);
    }

    // GET: Authors/Edit/5
    public ActionResult Edit(int? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Author author = db.Authors.FilterByOwner(User).FirstOrDefault(a => a.Id == id);
      if (author == null)
      {
        return HttpNotFound();
      }
      return View(author);
    }

    // POST: Authors/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit([Bind(Include = "Id,Email,RusSurname,RusInitials,RusOrgName,RusSubdivision,RusPosition,EnuSurname,EnuInitials,EnuOrgName,ScienceDegree,Phone,OrganizationKind,Postcode,PostalAddress")] Author author)
    {
      var userId = User.GetUserId();
      var orig = db.Authors.Include(a => a.Owner).FilterByOwner(User).FirstOrDefault(a => a.Id == author.Id);
      if (orig == null)
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

      Mapper.Initialize(cfg =>
          cfg.CreateMap<Author, Author>()
              .ForMember(dest => dest.Owner,    opt => opt.Ignore())
              .ForMember(dest => dest.OwnerId,  opt => opt.Ignore())
              .ForMember(dest => dest.Articles, opt => opt.Ignore())
              );

      Mapper.Map(author, orig);


      this.Revalidate(orig);

      if (ModelState.IsValid)
      {
        db.SaveChanges();
        return RedirectToAction("Details", new { id = author.Id });
      }
      return View(author);
    }

    // GET: Authors/Delete/5
    public ActionResult Delete(int? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Author author = db.Authors.Include(x => x.Articles).Include(x => x.Owner).FilterByOwner(User, Constants.AdminRole).SingleOrDefault(a => a.Id == id);
      if (author == null)
      {
        return HttpNotFound();
      }
      return View(author);
    }

    // POST: Authors/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int id)
    {
      Author author = db.Authors.Include(x => x.Articles).FilterByOwner(User, Constants.AdminRole).SingleOrDefault(a => a.Id == id);

      if (author.Articles.Any())
        return HttpNotFound("Нельзя удалять описание авторов для которого есть заявки на публикацию.");

      db.Authors.Remove(author);
      db.SaveChanges();
      return RedirectToAction("Index");
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing)
      {
        db.Dispose();
      }
      base.Dispose(disposing);
    }
  }
}

BlackHoles/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlackHoles.Controllers
{
  public class HomeController : Controller
  {
    public ActionResult Index()                   { return View(); }
    public ActionResult Oferta()                  { return View(); }
    public ActionResult Requirements()            { return View(); }
    public ActionResult FormattingRequirements()  { return View(); }
    public ActionResult FormattingExamples()      { return View(); }
    public ActionResult Conditions()              { return View(); }
    public ActionResult Prices()                  { return View(); }
    public ActionResult Antiplagiat()             { return View(); }
    public ActionResult ReviewRules()             { return View(); }
    public ActionResult Instruction()             { return View(); }

    public ActionResult About()
    {
      ViewBag.Message = "Об издательстве";

      return View();
    }

    public ActionResult Contact()
    {
      ViewBag.Message = "Контакты";

      return View();
    }
  }
}

BlackHoles/Controllers/IssuesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlackHoles.DataContexts;
using BlackHoles.Models;
using BlackHoles.Utils;

namespace BlackHoles.Controllers
{
  [Authorize(Roles = Constants.AdminRole)]
  public class IssuesController : Controller
  {
    private IssuesDb db = new IssuesDb();

    // GET: Issues
    public ActionResult Index()
    {
      return View(db.Issues.ToList());
    }

    // GET: Issues/Details/5
    public ActionResult Details(int? year, int? number)
    {
      if (year == null || number == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Issue issue = db.Issues.Find(year, number);
      if (issue == null)
      {
        return HttpNotFound();
      }
      return View(issue);
    }

    // GET: Issues/Create
    public ActionResult Create()
    {
      return View();
    }

    // POST: Issues/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create([Bind(Include = "Year,Number,Active")] Issue issue)
    {
      if (ModelState.IsValid)
      {
        db.Issues.Add(issue);
        db.SaveChanges();
        return RedirectToAction("Index");
      }

      return View(issue);
    }

    // GET: Issues/Edit/5
    public ActionResult Edit(int? year, int? number)
    {
      if (year == null || number == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Issue issue = db.Issues.Find(year, number);
      if (issue == null)
      {
        return HttpNotFound();
      }
      return View(issue);
    }

    // POST: Issues/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit([Bind(Include = "Year,Number,Active")] Issue issue)
    {
      if (ModelState.IsValid)
      {
        db.Entry(issue).State = EntityState.Modified;
        db.SaveChanges();
        return RedirectToAction("Index");
      }
      return View(issue);
    }

    // GET: Issues/Delete/5
    public ActionResult Delete(int? year, int? number)
    {
      if (year == null || number == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Issue issue = db.Issues.Find(year, number);
      if (issue == null)
      {
        return HttpNotFound();
      }
      return View(issue);
    }

    // POST: Issues/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int year, int number)
    {
      Issue issue = db.Issues.Find(year, number);
      db.Issues.Remove(issue);
      db.SaveChanges();
      return RedirectToAction("Index");
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing)
      {
        db.Dispose();
      }
      base.Dispose(disposing);
    }
  }
}

BlackHoles/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BlackHoles/Views/Home/Conditions.cshtml

@{ ViewBag.Title = "Порядок и условия публикации"; }

<div style="max-width: 900px; margin: auto;">
  @Shared.HomeTab(ViewContext.RouteData.Values["action"].ToString())

  <h3 class="text-center bold">Порядок и условия публикации статей в журнале @Constants.AdminRole, права и обязанности авторов</h3>

  <p>
    Право на публикацию в журнале имеют лица подписанные на журнал, представители организации подписанной на журнал (по одной публикации на одну подписку)
    или лицо оплатившее покупку одного или более авторского экземпляра номера журнала в котором публикуется его работа (@Html.ActionLink("стоимость и условия оплаты доступны по ссылке", "Prices")).
    <b><font color="red">Оплата авторского экземпляра производится после принятия</font></b> статьи к публикации.
  </p>

  <p>Заявка на публикацию статьи подается в электронном виде через автоматизированную систему на этом сайте. Подробности описаны в @Html.ActionLink("требованиях", "Requirements").

  <p>
    Согласно условиям @Html.ActionLink("лицензионного договора", "Oferta") Издательство как Лицензиат вправе использовать Произведение (статью и все входящие в нее составные части) на безвозмездной основе посредством:<br />
    а) воспроизведения (полное или частичное) Произведения в средствах массовой информации;<br />
    б) распространения экземпляров Произведения или его части любым способом;<br />
    в) импортирования экземпляров Произведения или его части;<br />
    г) переработки, в том числе перевода Произведения;<br />
    д) доведения Произведения или его части до всеобщего сведения.<br />
  <p>Автор несет персональную ответственность за содержание и оформление предоставляемых к публикации материалов, ответственность за содержание и оформление рецензии, ответственность за отзыв/рецензию на статью несут автор статьи и рецензент.
  <p>Автор несет ответственность за наличие в представляемом материале любых форм неправомерного заимствования. В случае обнаружения заимствования, не согласующегося с законодательством об авторском праве и смежных правах, материал отклоняется.
  <p>
    Заявка на публикацию материала, поступившая в адрес редакции по электронной почте/ через сайт/ лично через руководство Издательства, является конклюдентным действием,
    приводящим к возникновению указанных выше прав и обязанностей, расценивается как предложение автора о заключении лицензионного договора о предоставлении права
    использования произведения с Издательством, который в соответствии с п. 2 ст. 1286 Гражданского кодекса России может быть заключен в устной форме.
  <p>Также заявка на публикацию предполагает автоматическое согласие автора на публикацию материала на указанных условиях и в определяемые с учетом загруженности редакционного портфеля журнала сроки.
  <p>
    Лицензионный договор с автором статьи считается заключенным с момента принятия редакцией статьи к опубликованию и получения автором
    подтверждения от редакции по электронной почте.
  <p>Издательство имеет право уступить полученное от Автора право третьим лицам без предварительного согласования с Автором.
  <p>
    Издательство имеет право вносить необходимую корректуру в Произведение: аннотацию, ключевые слова, список литературы без согласования с автором,
    а также тексты переводов на английский язык.
  <p>
    Издательство предоставляет Автору электронную версию его статьи в формате PDF (вместе с оглавлением и титульным листом номера журнала).
    Если Автору требуется экземпляр журнала (бумажная версия) необходимо @Html.ActionLink("оплатить его пересылку", "Prices") по почте.

  @Shared.HomeLinks(ViewContext.RouteData.Values["action"].ToString())
</div>

BlackHoles/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Контакты";
}
<h2>@ViewBag.Title</h2>

<address>
  <b>Главный редактор</b> - Чистякова Людмила Александровна<br />
  <b>Контактный телефоны</b>: +7 (916) 320-71-78, +7 (499) 189-03-94.<br />
  <b>E-mail</b>: <a href="mailto:bp2702@yandex.ru">bp2702@yandex.ru</a><br />
  <b>E-mail</b> по вопросам, связанным с публикацией статей: <a href="mailto:vladdq@yandex.ru">vladdq@yandex.ru</a><br/>

  <b>Контактный телефон</b> издательства: +7 (916) 320-71-79, +7 (985) 064-35-38<br />
  <b>E-mail</b>: <a href="mailto:vlad@rsdn.org">vlad@rsdn.org</a><br />
    
</address>

BlackHoles/Views/Home/Index.cshtml
@using BlackHoles;
@using BlackHoles.Properties;
@using BlackHoles.Utils;
@using BlackHoles.DataContexts;
@{
    IssuesDb db = new IssuesDb();
    ViewBag.Title = "Публикация в журнале " + Constants.Jur;
    var activeIssueOpt = db.GetActiveIssueOpt();
}

<div style="max-width: 900px; margin: auto;">
  <p><a href="http://www.k-press.ru/bh/default-eng.asp">English version</a></p>

  <div class="row">
    <div class="col-lg-2">
      <img src="~/Images/k-press-logo.gif" class="img-fluid" alt="Responsive image" />
      @*<img src="" style="width:100%">*@
    </div>
    <div>
      <p>
        <b><font color="#003399">Ж</font></b>урнал <b>@Constants.Jur</b> публикует аналитические статьи, результаты фундаментальных теоретических и
        практических исследований в области российского законодательства и правоприменительной практики.
      </p></p>

      <p>
        <b>Внимание</b> с 1 января 2018 года журнал <b>НЕ</b> включен в перечень рецензируемых научных изданий ВАК. Все номера вышедшие до этого <A href="http://vak.ed.gov.ru/87">входят в перечень</A>
        под номером 1378 (<a href="http://www.k-press.ru/bh/scientific-specialties-classifier.html"><b>12.00.00 – юридические науки</b></a>).
        Журнал продолжает входить в <a href="https://elibrary.ru/project_risc.asp">РИНЦ</a>.
      </p>
    </div>
    </div>

    <p><A href="http://www.k-press.ru/bh/editorial-board.htm">Редколлегия журнала</A> <A href="http://www.k-press.ru/bh/editorial-board-eng.asp">(Editorial board - English)</A></p>

    <p>
      <b>Главный редактор</b>: Чистякова Людмила Александровна, <b><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span></b> +7 (916) 320-71-78, <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <a href="mailto:bp2702@yandex.ru">bp2702@yandex.ru</a>
    </p>

    <ul>
      <li><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;<a href='@Url.Action("Contact", "Home")' title="Телефоны, адреса электронной почты и другая информация">Контакты</a></li>
      <li><A href='@Url.Action("Requirements", "Home")'>Требования к статьям (рукописям), предоставляемым для публикации в журнал</A></li>
      <li><a href='@Url.Action("Conditions", "Home")'>Порядок и условия публикации статей, права и обязанности авторов</a></li>
      <li><a href='@Url.Action("ReviewRules", "Home")'>Правила рецензирования статей</a></li>
      <li>Индекс по <a href="http://www.rosp.ru/service/subscribe/">каталогу “Роспечать”</a> - <B>80270</B></li>
      <li>ISSN <b>0236-4964</b></li>
      <li><a href="http://www.k-press.ru/bh/Subscription.asp">Подписка</a></li>
      <li>Полные тексты статей<b> <a href="http://elibrary.ru/title_about.asp?id=7639">доступны на сайте РИНЦ</a></b> (Российского Индекса Цитирования).</li>
    </ul>

    @{
      const string ActiveTab = "ActiveTab";
      var activeTabCooke = Request.Cookies[ActiveTab];
      var activePan = int.Parse(activeTabCooke?.Value ?? "0");
      var issuesPanelClass   = activePan == 0 ? " in active" : "";
      var pubsPanelClass     = activePan == 1 ? " in active" : "";
      var learningPanelClass = activePan == 2 ? " in active" : "";

      var issuesTabClass     = activePan == 0 ? " class=active" : "";
      var pubsTabClass       = activePan == 1 ? " class=active" : "";
      var learningTabClass   = activePan == 2 ? " class=active" : "";
    }

    <ul class="nav nav-tabs">
      <li@(issuesTabClass)  ><a data-toggle="tab" href="#issuesPanel"   onclick="$.cookie('@ActiveTab', 0);"                    >Выпуски журналов</a></li>
      <li@(pubsTabClass)    ><a data-toggle="tab" href="#pubsPanel"     onclick="$.cookie('@ActiveTab', 1);" style="color: red;"><b>Опубликовать статью</b></a></li>
      <li@(learningTabClass)><a data-toggle="tab" href="#learningPanel" onclick="$.cookie('@ActiveTab', 2);"                    ><span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span> Инструкция</a></li>
    </ul>

    <div class="tab-content">
      <div id="issuesPanel" class="tab-pane fade@(issuesPanelClass)">
        <p></p>
        @Html.Partial("Issues")
      </div>
      <div id="pubsPanel" class="tab-pane fade@(pubsPanelClass)">
        <p></p>
       @if (activeIssueOpt == null)
       {
          <p class="alert alert-info">
            В настоящее время прием заявок на публикации статей неведется. Зайдите на сайт позже (через несколько дней).
          </p>
        }
        else
        {
          <p class="alert alert-info">
            Сейчас идет формирование № <b>@activeIssueOpt.Number</b> за <b>@activeIssueOpt.Year</b> год, который выйдет в <b>@Html.PublicationMonth(activeIssueOpt.Number))</b>.
            На этой странице вы можете подать заявку на публикацию в нем. Для этого нужно заполнить метаинформацию об авторах и подать электронную заявку на публикацию статьи.
          </p>
        }
        <p class="alert alert-success">
          В целях повышения удобства и качества обработки публикаций с 01.06.2017
          подача заявок на публикацию в юридическом журнале @Constants.Jur
          производится в электронном виде, через web-интерфейс.<br />
          Формы ввода снабжены подробными комментариями. Это делает
          процедуру подачи заявки на публикацию более однозначной и простой. <br />
          Если у вас возникли трудности, просмотрите @Html.ActionLink("ролики с инструкциями", "Instruction") или задайте вопрос по адресу <a href="mailto:vladdq@yandex.ru">vladdq@yandex.ru</a>.
        </p>

        @if (Request.IsAuthenticated)
      {
          <p>Сначала добавьте @Html.ActionLink("авторов публикаций", "Index", "Authors"), а потом
            @Html.ActionLink("заявки на публикации", "Index", "Articles") (где можно будет указать заранее введенных авторов).</p>
          <p>
            @if (User.IsInRole(Constants.AdminRole))
            {
              @Html.ActionLink("Номера", "Index", "Issues", null, new { @class = "btn btn-primary" })
            }
            @Html.ActionLink("Авторы статей", "Index", "Authors", null, new { @class = "btn btn-primary" })
            @Html.ActionLink("Статьи в формируемый номер", "Index", "Articles", null, new { @class = "btn btn-primary" })
          </p>
        }
        else
        {
          <p class="text-danger">Вы не произвели вход в личный кабинет (не авторизовались)!</p>
          <p>Чтобы добавить запрос на публикацию нужно @Html.ActionLink("войти в свой личный кабинет (авторизоваться)", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</p>
          <p>Если у Вас еще нет учетной записи, @Html.ActionLink("создайте новую учетную запись (зарегистрируйтесь в системе)", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" }).</p>
        }
    </div>
    <div id="learningPanel" class="tab-pane fade@(learningPanelClass)">
      <p></p>
      <span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span> @Html.ActionLink("Ролики демонстрирующие, добавление заявки на публикацию статьи и прочие операции со статьями", "Instruction").
    </div>
  </div>
</div>


BlackHoles/Views/Home/Requirements.cshtml
@using BlackHoles.Utils

@{ ViewBag.Title = "Требования"; }

<div style="max-width: 900px; margin: auto;">
  @Shared.HomeTab(ViewContext.RouteData.Values["action"].ToString())

  <h3 class="text-center bold">Требования к материалам, представляемым в журнал @Constants.Jur</h3>

  <p>Для публикации в журнале принимаются статьи в соответствии с тематикой журнала.</p>
  <p>Для публикации статьи в нашем издании вам нужно подать заявку на публикацию в электронном виде, через автоматизированную систему подачи заявок на публикацию.</p>
  <p>Если вы подаете заявку в первый раз, вам нужно создать учетную запись (зарегистрироваться). Это можно сделать @Html.ActionLink("здесь", "Register", "Account").</p>
  <p>Если вы уже подавали заявки на публикацию через автоматизированную систему, вам необходимо авторизоваться в системе (войти). 
  Это можно сделать @Html.ActionLink("здесь", "Login", "Account") или при обращении к формам требующим авторизации.</p>
  <p>Для подачи заявки на публикацию вам нужно:</p>
  <ol>
    <li>Ввести метаданные по каждому автору. Это можно сделать @Html.ActionLink("здесь", "Create", "Authors"). 
    Имеющийся список авторов можно просмотреть @Html.ActionLink("здесь", "Index", "Authors").</li>
    <li>Подать заявку на публикацию в текущий номер. Это можно сделать @Html.ActionLink("здесь", "Create", "Articles").
    Список поданных заявок можно просмотреть @Html.ActionLink("здесь", "Index", "Articles").</li>
  </ol>
  <p>В соответствии с требованиями ВАК и РИНЦ, вам необходимо предоставить метаданные и другие материалы:
    <ol>
      <li>Для каждого автора (описание автора может участвовать в более чем одной статье):
        <ol>
          <li><b>Адрес электронной почты</b>. Этот адрес будет указан в статье и на него будет отослан PDF статьи.</li>
          <li>Фамилия (<b>без сокращений в именительном падеже</b>).</li>
          <li>Имя, отчество (<b>без сокращений в именительном падеже, разделенные пробелом, сначала идет имя</b>).</li>
          <li>Место работы или место учебы в <b>именительном</b> падеже, <b>без указания структурных подразделений</b> (кафедры и т.п.).</li>
          <li>Ученое звание, учёная степень (через запятую, если имеется). *</li>
          <li>Должность *</li>
          <li>Структурное подразделение (кафедра, отдел, и т.п.). *</li>
          <li>Телефон. *</li>
          <li><b>Пункты 2-4 дублируются</b> на английском языке.</li>
        </ol>
      </li>
      <li>Для заявки на публикацию статьи:
        <ol>
          <li>Номер специальности (выбирается из списка <A href="http://www.k-press.ru/bh/scientific-specialties-classifier.html">научных специальностей</A>).</li>
          <li>Название статьи.</li>
          <li>Список авторов.</li>
          <li>Аннотация.</li>
          <li>Ключевые слова (порядка 1-6 слов/словосочетаний). Ключевые слова не должны быть предложениями, содержащими множество слов.</li>
          <li>Список литературы и документов, на которуые есть ссылки в тексте статьи.</li>
          <li>Текст статьи. Файл в формате Microsoft Word 97-2003 (предпочтительно), Microsoft Word 2007, rtf или txt.</li>
          <li>@Shared.Review(isFieldDesc: false)</li>
          <li><b>Пункты 2-4 дублируются</b> на английском языке.</li>
        </ol>
      </li>
    </ol>
    * – необязательно для заполнения поле (может быть пропущено). Однако – это не означает, что это поле не следует заполнять, в случае наличия информации.
  </p>
  
  <p>
    Статья <b>в обязательном порядке должна быть проверена</b> в системе <a href="http://www.antiplagiat.ru">http://www.antiplagiat.ru</a>.
    При проверке нужно использовать дополнительные модули: "<b>Коллекция LEXPRO</b>" и "<b>Коллекция eLIBRARY.RU</b>".
    При подготовке статей для защиты диссертаций нужно так же использовать модуль "<b>Коллекция диссертаций РГБ</b>".
    См. наши @Html.ActionLink("рекомендациями", "Antiplagiat").
  </p>

  <hr>

  <p>Статьи <b>без отзыва</b> или рецензии к публикации <b>не принимаются</b>!

  <p>
    Предоставляемые материалы должны быть актуальными, новыми (<b>оригинальными</b>, т.е.
    объем оригинального текста должен быть <b>@Constants.OriginalityPercentage%</b> или более), иметь научную или практическую
    <b>значимость</b>. <b><font color="red">Обратите внимание на то, что самоцитирование не является оригинальным материалом</font></b>
    и рассматривается как обычное цитирование. Текст, почерпнутый из других своих работ, нужно оформлять в виде цитат в соответствии с требованиями.
  <p>Статья <b>не должна содержать явных заимствований</b>, не выделенных в виде цитат со сносками 
  (см. <a href="@Url.Action("FormattingRequirements")">рекомендации по цитированию</a>).
  <p><b>Цитаты документов</b> и других правовых актов должны быть явно выделены в тексте 
  (см. <a href="@Url.Action("FormattingRequirements")">рекомендации по цитированию</a>). Не допускается изменение цитируемого текста.
  <p>
    Статья обязательно должна быть проверена системой @Shared.Antiplagiat().
    Перед проверкой обязательно ознакомьтесь с нашими <a href="@Url.Action("Antiplagiat")">рекомендациями</a> по проверке.
    Система @Shared.Antiplagiat() позволит вам определить процент оригинальности материала и наличия заимствований, не оформленных в виде цитат.
  <p>Редакция не выплачивает авторам денежные вознаграждения за предоставленные для публикации материалы.

  @Shared.HomeLinks(ViewContext.RouteData.Values["action"].ToString())
</div>